### ISSUE TITLE
[RFC] Configuration Management

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1012]
This is a rough suggestion of how we could handle configuration in Backstage. There's plenty more stuff to figure out, but this is just a request for comments :grin:

## Scope

The configuration solution would be used by all frontend code that's a part of a Backstage deployment, and should be a standardized API that plugins can rely on. In the backend, it's used to configure the main backend with plugins or other backends using `@backstage/backend-common`. Backends written in other languages are not in scope.

## Frontend

Configuration is accessed via a Utility API. It should be a synchronous API with typed access to config values. Missing values would always translate to `undefined`, and defaults would be done with the `??` operator.

Config would be backed by a JSON struct, and it should be possible to read values using a path, for example `'app.origin'`. It should also be possible to drill down into objects and use as if it was a top-level config.

For example something like this:

```ts
type Config = {
  getConfig(key: string): Config;
  getConfigArray(key: string): Config[];

  getNumber(key: string): number | undefined;
  getBoolean(key: string): boolean | undefined;
  getString(key: string): string | undefined;
  getStringArray(key: string, default: string[]): string[] | undefined;
  getDuration(key: string, unit: 'd' | 'h' | 'm' | 's' | 'ms'): number | undefined;
}

type ConfigApi = Config
```

## Backend

The interface for reading config would be similar to the frontend one, possibly with some more helpers like `getByteSize()`, `getDatabaseConfig()`. There would be some function(s) exported from
`@backstage/backend-common` for reading config files.

## Config Format

We don't necessarily enforce a format for configuration files. The only requirement is that config files
can be loaded and flattened into a single JSON struct at runtime.

For the default implementation I think YAML or HOCON would fit well. Most likely YAML, since we're already using it for the default entity descriptor format, and it makes sense to keep them similar.

## Config Example

Some things we likely want the config to support are:
  - Global config
  - Per-plugin config
  - Secrets read from env vars or files, or possibly other sources
  - Runtime config via env vars

This is a rough example what config could look like:

```yaml
version: 1

global:
  app:
    title: Backstage
    origin: http://localhost:3000

  backend:
    baseUrl: http://localhost:7000/api/

  organization:
    name: Spotify

packages:
  @backstage/auth-backend:
    providers:
      - type: 'google'
        environments:
          - name: dev
            client_id: x134v057bnt634fc834
            client_secret: 
              # Special key that provides different ways for reading secrets.
              # Secrets will never be sent to the frontend.
              $secret: 
                env: GOOGLE_AUTH_DEV_SECRET
          - name: prod
            client_id: i0c3597qhn0q395g7cq
            client_secret:
              $secret:
                file: /etc/secrets/google_auth_prod_secret

  @backstage/catalog-backend:
    database:
      type: postgres
      host: postgres
      port: 4567
      user: postgres
      password:
        $secret:
          # Using an opaque ID could allow us to hook in any secrets provider, e.g. hashicorp vault
          provided: postgres-password
```

It would then be possible to override at least some of these values at runtime, for example setting `CONFIG_APP_ORIGIN=http://localhost:4000` would override the global `app.origin` config.

I'm not sure about how config would be merged and scoped, and I think the implementation we choose might influence that a bit. One possibility would be that per-package config is merged into the global config and provided to each package as a single object.

## Suggested Implementation

The first thing to explore would be existing npm packages that could support our use-case. The package could likely be used as a build-time dependency for the frontend, and runtime for the backend.

For loading the config into the frontend I think we don't need to require a single method, and could provide different implementations for accessing the config. That said I think we could ship a default implementation that serves the config as JSON from the nginx container we deploy the frontend from, and then injects runtime config from the environment into that JSON blob at startup.

In the backend I expect that we just read the config directly for each package.

**Comment by Rugvip** [comment]
Not mentioned above, but thinking that we would also add optional config schemas via JSONSchema.

**Comment by dtuite** [comment]
Only thing I would home, and I'm sure you were thinking this way already, is that it's mostly run time config.

For example, imagine a config where you set the name of your company so it shows up in the header in the application or something. It might be tempting to make this build time config where you would pass it in like this

```
npx @backstage/cli create-app big-co --title "Big Company"
```

but IMO there is no reason not to make this run time config so I can more easily change the title in the header to something else.

**Comment by Rugvip** [comment]
@dtuite Yeah runtime config is the main use-case. I think it should for example be possible to set an `CONFIG_ORGANIZATION_NAME` env var in the container used to server the frontend, and have that show up when a plugin in the frontend does `configApi.getString('organization.name')`.

Regarding create-app I think we can expand the capabilities of that quite a bit once we have something like this in place.

**Comment by Rugvip** [comment]
As mentioned by @freben in #1046, we might want to provide a `defaultValue` parameter to each accessor.

The RFC mentions `??` as the solution to defaults, as I liked the idea of relying on language features instead of API. Kinda like if you'd build a config lib in Java you'd likely use Optional now, instead of a default param.

The thing speaking against that for me is if you want to throw an error when the value is missing, it's a bit annoying to have to check for undefined separately and then throw. https://github.com/tc39/proposal-throw-expressions would kinda solve it, but you still have to come up with your own error message. If we add a default param, I'd want to treat it as the switch for whether to throw if the value is missing, so if the value is missing and no default is given, throw.

One alternative to the throw-on-missing-without-default behavior could be to provide `must*` variants of all methods, e.g. `mustString(key: string): string`. That solution is something that would be possible to add later if we feel we need it, and imo it's also a bit nicer than overloading the methods, as overloads are a bit wonky in TS.

**Comment by Rugvip** [comment]
So the basis for this has been around for a while, but we're still lacking two things (imo). The most clear one would be env-based config, or multiple/layered config files. Things like `app-config.yaml` + `app-config.development.yaml` + `app-config.development.local.yaml` etc. All of that is really in place in the `config-loader` package, and the only thing that's needed is the resolve logic, preferably using some existing logic in the node ecosystem.

The other piece is config scoping, for example global + local config for plugins. My thinking has been that we'd layer them on top of each other with plugin-specific config overriding the global one, so for example if the `catalog` plugin does `config.getString('app.title')` with the following config:

```yaml
app:
  title: Foo

plugins:
  catalog:
    app:
      title: Bar
```

it would receive `'Bar'`.

This avoids having to pass around two config objects (a global and a local one), but I also think it is a bit too magical and error prone imo.

A middleground solution that just popped into my mind is to use a top-level `'plugin'` key to access the plugin config, so in the above example for the catalog plugin would be `config.getString('app.title') === 'Foo'`, and `config.getString('plugin.app.title') === 'Bar'`. I'm hoping that provides the namespacing and utility of accessing a single config object, but is still intuitive enough to understand when looking at the combination of code and config yamls.

Thoughts? :grin:

**Comment by andrewthauer** [comment]
I think it depends on if the plugins should be able to override the global settings. Is so, then I think the key being used in the config api needs to be used the same (e.g. `app.title`). That way it can use the more specific case and fallback to the global if not provided. However, I'm struggling a little bit to come up with a real world use case where I would want to have the plugin override a global setting. I'm sure there are potential cases, but seems like a less common use case to me.

**Comment by andrewthauer** [comment]
Another thing that I wanted to point out, is the config file format seems to be going in the direction where both the frontend & backend configurations would be in a single file by convention. While this makes configuration easier to maintain, it could lead to certain backend values (e.g. secrets) accidentally leaking into the frontend bundles.

I've noticed the config API already picks up environment variables automatically via a convention (e.g `APP_CONFIG_parentKey_subKey` accessed by `getString('parentKey.subKey')`). This allows for a lot of flexibility and can be used as a technique to mix and match with config & environment variables are used for each (frontend vs backend). However, I've been consciously avoiding using the prefix `APP_CONFIG_` for environment variables used by the backend to ensure these are not picked up automatically. This means I'm not using the config API for backend secrets at the moment.

Also, the original proposal has the concept of a `$secrets` key, which seems interesting. Would the intention be there would be some common tool that parses this and knows not to send the secrets to the app bundle? Currently the example dockerfile uses `jq` to inject the config as json into the app bundles, which wouldn't be a good gate keeper of secrets imo. 

I guess what I'm ultimately getting at, is with too many ways to access and setup config values, it becomes hard to reason about where they are coming from and how they are used.

**Comment by Rugvip** [comment]
@andrewthauer Yeah I'm not completely convinced that having a completely common config for frontend and backend is the way to go. For example there could be some explicit separation and then inheritance (yaml anchors?) to reuse bits. The original proposal here does have that separation. That said I think it does make the config a lot simpler, even if the frontend bundle ends up being a bit larger.

Regarding secrets, it's actually already implemented in the [config-loader](https://github.com/spotify/backstage/blob/5e36d0cf2806f8489a7986f930662212cba1f834/packages/config-loader/src/loader.ts#L57). Secrets are only read into the Backend config, so they won't be shipped to the frontend. It's a valid point about env var confusion though, and It may be a good idea to not allowing a config key that at some point was defined as a secret to be overridden by a non-secret value. Otherwise someone is likely to set `APP_CONFIG_plugins_auth_providers_google_development_clientSecret=...` and expose it to the frontend at some point ^_>. Also see #1680 as it introduces way more usage of config and secrets.

Regarding `APP_CONFIG_` env var in general I think they should be used as sparingly as possible. They're basically only there to allow a single build artifact to be run in a couple of different environments, e.g. switching out `baseUrl`s to run a production image in a staging environment first. As well as temporary config tweaks for local development and scripts. The idea is really that config should be done through static files and checked in to the app repo.

**Comment by andrewthauer** [comment]
@Rugvip - I think what your proposing makes sense. The only `APP_CONFIG_` based environment variable I'm using now is `APP_CONFIG_backend_baseUrl` which would allow for the single build artifact to be used in different environments. Having backend secrets not use the `APP_CONFIG` prefix seems like the ideal pattern to avoid confusion.

**Comment by Rugvip** [comment]
Current implementation is now documented at https://github.com/spotify/backstage/blob/master/docs/conf/index.md

It implements pretty much all of this and a bit more, except for the scoped configuration. I'm a bit torn whether it's something we want or not. Right now the pattern is to use top-level keys like `catalog` or `auth` instead of `plugins.catalog`, `plugins.auth`. I think the original suggestion in this RFC to use packages as the namespace doesn't make sense, but using the plugin ID may still be quite useful.

My primary worry about not having clear sub-sections for different plugins is that over time the required configuration with become one big entangled mess. We can help out a bit with schema definitions and whatnot, hopefully being able to identity things that extraneous keys from plugins that where removed. I'm still a bit worried that won't be enough though, and that it would be better to have a clear separation of configuration for each plugin.

@spotify/backstage-core and others, thoughts? :grin:

**Comment by dtuite** [comment]
@Rugvip  Here's how I'm doing config for a Helm driven kubernetes deployment of Backstage. A real world example might help drive decision making.

I have a vanilla `app-config.yaml` except for two properties I added: `backend.lighthouseHostname` and `backend.gitopsHostname`. [source](https://github.com/RoadieHQ/backstage/blob/kubernetes-demo/app-config.yaml)

I have hacked in SSL verification support and camelCased postgres variable names. The camelCasing will be important in a second. [source](https://github.com/RoadieHQ/backstage/blob/kubernetes-demo/packages/backend/src/index.ts#L60)

```ts
      knexConfig = {
        client: 'pg',
        useNullAsDefault: true,
        connection: {
          port: config.getOptionalNumber('backend.postgresPort'),
          host: config.getString('backend.postgresHost'),
          user: config.getString('backend.postgresUser'),
          password: config.getString('backend.postgresPassword'),
          // database: `backstage_plugin_${plugin}`,
          database: config.getString('backend.postgresDatabase'),
          ssl: {
            ca: fs.readFileSync(config.getString('backend.postgresPathToCa')),
            rejectUnauthorized: true,
          },
        } as PgConnectionConfig,
```

My app config is overridden with environment variables in my Helm chart, which lays down a `configmap` in k8s. [source](https://github.com/RoadieHQ/helm-charts/blob/master/backstage/templates/config.yaml)

This shows the problem with `UPPERCASE` postgres config variable names. They are incorrectly parsed by the config loader!

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-app
data:
  APP_CONFIG_app_baseUrl: {{ .Values.appConfig.app.baseUrl | quote | quote }}
  APP_CONFIG_app_title: {{ .Values.appConfig.app.title | quote | quote }}
  APP_CONFIG_backend_baseUrl: {{ .Values.appConfig.backend.baseUrl | quote | quote }}
  APP_CONFIG_backend_lighthouseHostname: {{ .Values.appConfig.backend.lighthouseHostname | quote | quote }}
  APP_CONFIG_backend_gitOpsHostname: {{ .Values.appConfig.backend.gitOpsHostname | quote | quote }}
  APP_CONFIG_backend_listen: {{ .Values.appConfig.backend.listen | quote | quote }}
  APP_CONFIG_backend_cors_origin: {{ .Values.appConfig.backend.cors.origin | quote | quote }}
  APP_CONFIG_backend_postgresUser: {{ .Values.appConfig.backend.postgresUser | quote | quote }}
  APP_CONFIG_backend_postgresPort: {{ .Values.appConfig.backend.postgresPort | quote }}
  APP_CONFIG_backend_postgresDatabase: {{ .Values.appConfig.backend.postgresDatabase | quote | quote }}
  APP_CONFIG_backend_postgresHost: {{ .Values.appConfig.backend.postgresHost | quote | quote }}
  APP_CONFIG_backend_postgresPathToCa: {{ .Values.appConfig.backend.postgresPathToCa | quote | quote }}
  APP_CONFIG_sentry_organization: {{ .Values.appConfig.sentry.organization | quote | quote }}
  # loads of variables omitted for brevity
```

These configs are picked up by my deployments. [source](https://github.com/RoadieHQ/helm-charts/blob/master/backstage/templates/deployment.yaml#L70)
