### ISSUE TITLE
[catalog-backend] Fan-Out/Nested Location Fetching

### ISSUE THREAD

**Issue by daviddyball** [spotify/backstage#1236]
## Feature Suggestion

Add support for referencing a `location` which is a list of more `locations` to fetch (with a max-deplth limit for sanity).

e.g. I submit a location like so:
```
{
  "type": "github",
  "target": "https://github.com/myorg/services-list/blob/master/services.yaml"
}
```
Inside the `services.yaml` file I'd like to list more locations to fetch from, like so:
```
apiVersion: backstage.io/v1beta1
kind: Location
metadata:
  name: service-a
spec:
  type: github
  target: https://github.com/myorg/service-a/blob/master/meta.yaml
---
apiVersion: backstage.io/v1beta1
kind: Location
metadata:
  name: service-b
spec:
  type: github
  target: https://github.com/myorg/service-b/blob/master/meta.yaml
---
apiVersion: backstage.io/v1beta1
kind: Location
metadata:
  name: service-c
spec:
  type: github
  target: https://github.com/myorg/service-c/blob/master/meta.yaml
```

I saw https://github.com/spotify/backstage/issues/1013, but that didn't seem like the same idea, so I wanted to post this as a separate feature-request

## Possible Implementation

Add support for the `LocationReader` implementations to read `kind: Location` from upstream `Locations` to support mixed content.

Example:
```
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: my-service
spec:
  type: service
---
apiVersion: backstage.io/v1beta1
kind: Location
metadata:
  name: service-a
spec:
  type: github
  target: https://github.com/myorg/service-a/blob/master/meta.yaml
```

## Context

Our developers currently maintain a set of service meta-data and are generally good at keeping it up-to-date as it lives in their service codebase. If we move it out to a central place so we can reference it in a single `location` then there is the possibility of it going stale or losing sync with the services themselves.

The other option is to add 300+ `locations` to the `catalog-backend`, but that doesn't seem like a good ide (correct me if I'm wrong)
