### ISSUE TITLE
Move Template Definitions into the Service Catalog

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1301]
We'd like to add a more flexible model to the `template-info.json`, but it's going to be much easier in the long run to create these as definitions in the Service Catalog, as things like `ownerId` and `tags` we could get for free.

## Feature Suggestion
- Move `template-info.json` definitions to the Service Catalog
- Be able to search the the Service Catalog instead for the listing of templates
- Get the location for this Template somehow?

## Possible Implementation
```json
{
    "id": "react-ssr-template",
    "name": "SSR React Website",
    "description": "Next.js application skeleton for creating isomorphic web applications.", 
    "ownerId": "something"
}
```

Becomes something like this:

```yaml
apiVersion: backstage.io/v1beta1
kind: Component
metadata:
  name: react-ssr-template
  description: Next.js application skeleton for creating isomorphic web applications.
spec:
  type: template
  lifecycle: experimental
  owner: tools@example.com
  label: React SSR Template
  tags:
    - React
    - CookieCutter
    - Golden Path
```

This would then be used in the listing of templates in the Scaffolder component.

### Questions
- How do we find the template location in the Service Catalog, can we maybe get it from the `Location` already stored?
- Should this be `kind: Component` or `kind: Template`

@freben i'd be interest to hear how you think this could work
