### ISSUE TITLE
Better support for multicomponent

### ISSUE THREAD

**Issue by JordiPolo** [spotify/backstage#1330]
As per @freben  (if I understood correctly) I'm trying to divide a service which provides both an API and renders an UI.

It is ackward to describe
```yaml
---
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: this_owner
metadata:
  name: Zipkin-api
  description: Opensource tracing solution API.
---
apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  type: service
  lifecycle: production
  owner: this_owner
metadata:
  name: Zipkin-ui
  description: Opensource tracing solution UI.
```

Two big issues:
- Note that there are 2 changes and lots of copy paste. This is ever worse because we have in our format links to documetation, information about slack, story board, etc. All that needs to be copy/pasted as belongs to both.

- We use and know what's "zipkin" but now does not really exist. We have zipkin-api  and zipkin-ui which because of the copy paste clearly are related but does not match my mental model of what's out there.
