### ISSUE TITLE
[RFC] Catalog Organizational Data

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1401]
# Context

We currently don't have any real model for identities or organizational data within Backstage. We're allowing login via various identity providers and can access those identities in the frontend, but there's nothing tying these identities to ownership in the catalog, or additional metadata. The idea is that an organization using Backstage should be able to bring in this data from an existing system, for example GitHub org data, LDAP or GSuite.

There are some initial experiments with an identity service, which is our initial approach, but looking at the problem of modelling identities it has a lot of common requirements with the catalog service.

# Existing Implementation

Our internal implementation talks to an in-house identity service which in turn connects to many other systems. From that service we fetch and cache data about users and groups in the system. Very little of the metadata about the users and groups is actually stored and consumed in Backstage, as it's mostly limited to organizational structure in order to determine who owns and maintains the different components.

Even though there is a separate identity service and the organizational data is never pulled into the core entity model, we still end up modelling the data in a similar way to other entites e.g. for searching and presentation in the frontend.

# Proposed Solution

We model both identities and organizational data in the catalog by defining two new kind of entities, `User` and `Group`. A User represents a person within an organization, which in turn might have many identities. A group is any kind of organizational structure which in turn can contain other groups or users.

Both users and groups within the catalog would serve as read-only representations, an adapter that provides a common model for that type of data within backstage. It would be a very slim model that doesn't contain much actual information about users. If an organization wishes to visualize and/or manage user or group data from within Backstage, that would be through a separate plugin that makes direct calls to the management service.

## Benefits

Looking at the identity service requirements it shares a lot of desired functionality with the catalog. We want to have multiple different models for pulling in organizational data, such as directly calling out to services, push- or pull-based ingestion, or even syncing with code repositories. These are all problems that we're looking to solve with the catalog service as well, meaning there's a lot of overlap between the two.

## Drawbacks

We will want to keep the catalog APIs general-purpose, meaning that would **not** want to add endpoints like "all components that this user owns". At least short term it will make a lot of queries awkward with multiple requests to do relatively simple queries. The plan is to relatively soon introduce a GraphQL layer which would solve this issue.

We would likely also have to introduce some security features to the catalog that for example forbids some locations from defining some kind of components. We wouldn't for example want to allow anyone in an organization to create a yaml with a user declaration in it and add it to the catalog.

## Data Model

Below are two example schemas for the new `User` and `Group` kinds. They are not examples of what someone would write by hand, but a model of what would be generated by an automated ingestion solution. That said it can still be hand written for demo purposes or easier onboarding of smaller organizations.

The schema is highly denormalized, as the purpose of the entities is to serve as a read-only view of organizational data that is ingested from another source. We would likely provide generic user and group transforms in the catalog that is able to denormalize ingested normalized data.

### User Example

```yaml
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  # This would be **the** user ID within Backstage, and
  # what is returned when you call identityApi.getUserId()
  name: john

spec:
  # This would be a minimal profile structure that is shared
  # with the profile structure we use in the auth backend
  # for various providers. Any additional profile fields
  # like telephone number would go in the metadata, likely
  # as labels or annotations.
  profile:
    displayName: John Doe
    email: john.doe@example.com
    picture: https://example.com/avatars/john.doe

  # This will be used during sign-in to tie an external identity to this one.
  # Most deployments should only need a single identity
  # and selected login provider. But there could be use-cases
  # for allowing multiple sign-in identities.
  identities:
    - type: google
      id: 359867349587
      email: john.doe@gmail.com
    - type: github
      login: john

  # Some form of group membership information, we could try out
  # a simple flat structure and see if that's enough.
  # Although it would probably be best to come up with a common
  # schema for modeling relationships between entities.
  groups:
    - doe-squad
    - example
    - employees
```

### Group Example

```yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: doe-squad
  title: Doe Squad
  description: A squad for John and Jane
spec:
  # Org-specific type, similar to Component
  type: squad # could be things like 'root', 'business-unit', 'mission', 'product-area', 'temporary'

  # Just like user memberships we could keep this simple, but
  # hopefully end up with a common way of modelling this for
  # all kinds of entities.
  #
  # To make it simple to write these definitions by hand, we
  # could allow for only parents or children to be
  # specified, and then derive the rest from that information.
  parent: [group-a]
  ancestors: [group-a global-synergies, acme-corp]
  children: []
  grandchildren: []

  # Membership information. Just like above this is denormalized
  # and we could derive it from user group memberships, or the other way around.
  members:
    - john
    - jane
```

**Comment by freben** [comment]
Initial thoughts:

The `identities` field sounds a lot like what selector labels are for, and they could be nicely namespaced and semantic.

```yaml
metadata:
  labels:
    google.com/email: john.doe@gmail.com
    github.com/login: john
```

Like I mentioned in a different discussion, I find it an interesting idea to autogenerate things like this FROM the spec, where possible. But that's going a bit farther.

Regarding User `spec.groups` Group `spec.members`, one may want to supply both the immediates and the recursively descended versions of both of those.
