### ISSUE TITLE
Create a proxy

### ISSUE THREAD

**Issue by marcuseide** [spotify/backstage#1440]
## Feature Suggestion

Create a `proxy-backend` or similar that allows the frontend to make HTTP API calls to a backend without having to worry about CORS or SSL(?).

## Possible Implementation

A proxy which reads config from `app-config.yaml`. The config would probably be keyed on service and endpoint.

Something like:
```yaml
proxy:
  baseUrl: "http:localhost:7000/proxy"
  service1:
    /some/endpoint:
      target: "http://localhost:7000"
      rewrite: "/api/some/endpoint"
      headers:
      - Access-Control-Allow-Origin: "*"
      timeout: 240
  service2:
    /some/secondEndpoint:
      target: "https://example.com"
      ssl: true
```

Possibly use [express-http-proxy](https://www.npmjs.com/package/express-http-proxy) or similar if that makes sense.

## Context

Move proxy configuration away from `package.json` and make it more configurable.
