### ISSUE TITLE
RFC: Github Authentication for Backend Plugins

### ISSUE THREAD

**Issue by benjdlambert** [spotify/backstage#1565]
## Context
Backstage is always going to treat Github as a first class citizen, and have first class support for any interaction between the two. Github's authentication is at the best of times complex with different scopes for access tokens, personal access tokens, Github Apps, and Github O-Auth apps. This RFC's purpose is to decide on a best way to manage this authentication from backend plugins in the Backstage ecosystem.

## Existing Implementation
So, currently, there isn't a standard one. We use the simplest of authentication methods that posed the least resistance when getting up and running with something. These are called [Personal Access Tokens](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token). They are then used with the `GITHUB_ACCESS_TOKEN` environment variable and then the Backstage plugins will just read from this variable.

These tokens are given scopes as to what they can access, but they can access whatever the user can in that scope. You cannot have fine grained control as to what Repositories or Organisations the token can read and write to. If the user can do it, and it has the scope, then it should work.

This approach has it's downfalls. It's annoying to have to create access tokens and then storing this access token somwhere for you to run can also be a pain.

## Proposed Solution
[Github Apps](https://developer.github.com/apps/about-apps/) are a really nice way to create tokens which have fine grained permissions to the place that it has been installed. This will allow us to register the same application throughout the entire of the users organisation, wether that be personal repositories, or organisations as a whole. Once granted into a particular install place, the backend plugins can request a token for that installation.

For example:
- I create a new Github App called `TestApp`.
- `TestApp` will then get installed into my `org` `TestOrg` of which I am a member of, but not `TestOrgBlocked` which I am also a member of.
- Backstage plugins can request a token for operations on `TestOrg` but not on anything that is in `TestOrgBlocked` as although I might have been the owner or creator, the token is only valid to the place I install it.

Another benefit of using Github Apps, is that installing the app will automatically register a webhook for all events that are also requested from the App. This is a real benefit for the Backstage ecosystem, as we can move a lot of the data flow to an Event Driven Push model, rather than polling for things.

[ProBot](https://probot.github.io) is a really good example of Github Apps working in perfection and has a great API for dealing with webhook events.

### Benefits
- Fine grained access control
- Users are not tied to access keys (when a user gets removed from the org, it still works)
- Webhook Events + Read Write permissions are much more clearer than oauth scopes.
- This authentication can be shared throughout plugins

### Drawbacks
- Setting up a GithubApp can be challenging
- For internal deployments and webhooks to work, might need to run a proxy which can proxy from a public URL to internal webhook listener as github can't send events to `http://localhost:8000/blah`.

### Creating Github Apps
It would be really great if we could just have a Backstage App in the Github Marketplace that you can install into your organisation, but the problem is, is that we don't provide the backend. The user brings their own, so they need their own version of a Backstage plugin so that the credentials for access to their organisation is passed to their own App backend rather than it being passed to some backend like in SASS.

As mentioned from before [ProBot](https://probot.github.io) is a really good example of using Github Apps for your own use, I tried to get setup with this, but turned out that I couldn't directly access the token for an installation of the app which was a little bit of a blocker when not everything is event driven. 

I started to tear apart how the creation of a plugin works in ProBot and managed to replicate something similar with a frontend and backend plugin in Backstage as a POC.

The flow for the end user looks like this:

- User clicks a button to `Create Github App` inside backstage
- User is sent to Github to give the Github App a name
- Once the App has been created, the user will be then be prompted where to install the app
- Once the app has been installed, then the backend has access to the installed places.

The more technical flow looks like this:
- *User clicks a button to `Create Github App` inside backstage*
  - Under the hood, this uses `POST` to the Github App with a [Github App Manifest](https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/).
  - This basically means that we can create a template for the user to create a Github App from, all they need to do is give it a unique name. The Github App Manifest will basically also setup some basic permissions and webhook events that the Backstage App will need to run.
- *User is sent to Github to give the Github App a name*
  - The manifest is accepted by github and using the `callback_url` will deliver the payload to the running Github App Backend. I created one on `http://localhost:7000/gh-app/callback`. It receives the `private_key` `id` `client_secret` `client_id` that is all needed to create requests to the github api on behalf of the installation.
- *Once the App has been created, the user will be then be prompted where to install the app*
  - When the app has been installed, it will send an `create` event for the installation to the webhook route `http://localhost:7000/gh-app/events` with the `installation_id` which is the last part needed to generate tokens to hit the github API for the app.

Some libraries that I used which were useful:
https://github.com/octokit/app.js/
https://github.com/octokit/auth-app.js/
https://github.com/octokit/request.js/

Here's what a sample manifest can look like (very similar to the ProBot one).
```yml
# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
# Uncomment the event names below to enable them.
default_events:
  - create
  - delete
  - push
  - repository

  # - issues
  # - check_run
  # - check_suite
  # - commit_comment
  # - deployment
  # - deployment_status
  # - fork
  # - gollum
  # - issue_comment
  # - label
  # - milestone
  # - member
  # - membership
  # - org_block
  # - organization
  # - page_build
  # - project
  # - project_card
  # - project_column
  # - public
  # - pull_request
  # - pull_request_review
  # - pull_request_review_comment
  # - release
  # - repository_import
  # - status
  # - team
  # - team_add
  # - watch

# The set of permissions needed by the GitHub App. The format of the object uses
# the permission name for the key (for example, issues) and the access type for
# the value (for example, write).
# Valid values are `read`, `write`, and `none`
default_permissions:
  # Repository creation, deletion, settings, teams, and collaborators.
  # https://developer.github.com/v3/apps/permissions/#permission-on-administration
  # administration: write

  # Checks on code.
  # https://developer.github.com/v3/apps/permissions/#permission-on-checks
  # checks: read

  # Repository contents, commits, branches, downloads, releases, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-contents
  contents: read

  # Deployments and deployment statuses.
  # https://developer.github.com/v3/apps/permissions/#permission-on-deployments
  # deployments: read

  # Issues and related comments, assignees, labels, and milestones.
  # https://developer.github.com/v3/apps/permissions/#permission-on-issues
  # issues: write

  # Search repositories, list collaborators, and access repository metadata.
  # https://developer.github.com/v3/apps/permissions/#metadata-permissions
  metadata: read
  # Retrieve Pages statuses, configuration, and builds, as well as create new builds.
  # https://developer.github.com/v3/apps/permissions/#permission-on-pages
  # pages: read
  # Pull requests and related comments, assignees, labels, milestones, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests
  # pull_requests: read
  # Manage the post-receive hooks for a repository.
  # https://developer.github.com/v3/apps/permissions/#permission-on-repository-hooks
  # repository_hooks: read
  # Manage repository projects, columns, and cards.
  # https://developer.github.com/v3/apps/permissions/#permission-on-repository-projects
  # repository_projects: read
  # Retrieve security vulnerability alerts.
  # https://developer.github.com/v4/object/repositoryvulnerabilityalert/
  # vulnerability_alerts: read
  # Commit statuses.
  # https://developer.github.com/v3/apps/permissions/#permission-on-statuses
  # statuses: read
  # Organization members and teams.
  # https://developer.github.com/v3/apps/permissions/#permission-on-members
  # members: read
  # View and manage users blocked by the organization.
  # https://developer.github.com/v3/apps/permissions/#permission-on-organization-user-blocking
  # organization_user_blocking: read
  # Manage organization projects, columns, and cards.
  # https://developer.github.com/v3/apps/permissions/#permission-on-organization-projects
  # organization_projects: read
  # Manage team discussions and related comments.
  # https://developer.github.com/v3/apps/permissions/#permission-on-team-discussions
  # team_discussions: read
  # Manage the post-receive hooks for an organization.
  # https://developer.github.com/v3/apps/permissions/#permission-on-organization-hooks
  # organization_hooks: read
  # Get notified of, and update, content references.
  # https://developer.github.com/v3/apps/permissions/
  # organization_administration: read

# Name of the github app
name: Backstage

# The homepage of your GitHub App.
url: https://backstage.io

# A description of the GitHub App.
description: The Github App for Backstage
# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
public: false
```
