### ISSUE TITLE
RFC: Support static configuration of catalog location entries

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1833]
## Feature Suggestion

Right now all catalog locations need to be added either in code using a static catalog class, or registered by a user or script in the location database. I'm thinking it would be useful to allow locations to be registered via static configuration as well, to support a couple of different use-cases:

- Seeding the catalog for demo and local dev purposes.
- Configuration of integrations with external systems from which we want to pull data into the catalog.
- More visible configuration and improved robustness of repo-wide scanning or "catalog repos", for example for pulling in all API declarations from a gRPC protobuf repo.

## Possible Implementation

Add a `catalog.locations` (or `plugins.catalog.locations`?) config entry that is read by the catalog backend. The config would match the `spec` part of `Location` entities, something like this:

```yaml
catalog:
  locations:
    - type: github
      target: github.com/spotify/backstage/apis/**/catalog-info.yaml
    - type: ldap
      target: ldap://ds.example.com:389/dc=example,dc=com
    - type: github-org
      target: github.com/spotify
```

Forgive me if the `ldap` example isn't correct, not too familiar with that 😅 

With support for this we could also extend the `create-app` template to include locations of some of the example `yaml`s in this repo, both components and scaffolder templates. It's then also really simple to get rid or change the examples if desired, as you just need to edit your local config.

## Context

Discussions around the use-cases mentioned above:
- https://github.com/spotify/backstage/pull/1823
- https://github.com/spotify/backstage/issues/1824
