### ISSUE TITLE
Catalog: support mapping of allowed entity kinds per location type

### ISSUE THREAD

**Issue by Rugvip** [spotify/backstage#1853]
## Feature Suggestion

Add support for limiting the allowed location types for each kind of entity. A configuration could look something like this:

```yaml
entity-restrictions:
- kind: [User, Group]
  locations:
  - type: ldap
  - type: github-org
```

We'd also probably want to allow exceptions for some targets, maybe something like

```yaml
entity-restrictions:
- kind: [User, Group]
  locations:
  - type: github
    target: github.com/acme-co/org-data/users.yaml
  - type: github
    target: github.com/acme-co/org-data/groups.yaml
```

## Possible Implementation

Most likely implemented as a Processor in the catalog, preferable as a standalone thing that doesn't depend on other processors.

## Context

The primary purpose of this is to enable https://github.com/spotify/backstage/issues/1401 in a secure way. If we don't add any restrictions to how entities can be defined, it would be possible for anyone to create a `User` entity with any kind of metadata. That in turn could be used to gain access to other users' accounts, and wreak havoc in general.

**Comment by freben** [comment]
If I interpret the above correctly, it would suffice to whitelist only for example Component from any source. Then User and Group would be added only through a config based route, which never has any restrictions on it (because it's added by infra teams so should not need to pass through these same rulesets). Does that make sense? In a default-deny scenario.

**Comment by Rugvip** [comment]
@freben I figured it makes sense to do default-allow. Since most entities will be completely fine to allow, and there's less overhead for defining new entities. It does come with the risk of people accidentally removing the User and Group restriction though. If we want to protect against that we could make those a bit special and default to them being completely denied.

Regarding implicit allow from config-based locations I was thinking that too, but not sure we can do that. It kind of removes the possiblity of using config-based routes for other types, as you'd be able to sneak in Users in a configured API repo for example. I think we can work with that to possibly make it a bit simpler though, instead of having to list the location twice. Something like

```yaml
locations:
- type: github
  target: github.com/acme-co/org-data/users.yaml
  allow: [User]
```

**Comment by freben** [comment]
or as a full allow/deny chain, that gets iterated from top to bottom looking for matches, and comes preinstalled with only one allow-all or deny-all rule :)

```yaml
rules:
  - type: github
    target: github.com/acme-co/org-data/users.yaml
    allow: [User]
  - type: github
    deny: [User]
  - allow: [*]
```

or whatever
