### ISSUE TITLE
GraphQL SDL API Docs Support

### ISSUE THREAD

**Issue by andrewthauer** [spotify/backstage#2111]
The recent `api-docs` plugin is a great addition. Having support for viewing GraphQL SDL schemas would be great. I've experimenting with this idea in #2088

## Feature Suggestion

Given the following API entity:

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: some-service-graphql
  description: A services GraphQL API
spec:
  type: graphql
  definition: |
    schema {
      query: Root
    }   
    ...
```

There would be a viewer similar to `openapi`, & `asyncapi` for rending the GraphQL SDL schema docs. Possibly something like:

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/6507159/91168863-56974280-e6a4-11ea-940a-aa23f9ab739d.png">

or 

<img width="1647" alt="image" src="https://user-images.githubusercontent.com/6507159/91168955-7c244c00-e6a4-11ea-91f2-599446c64543.png">

## Possible Implementation

See #2088 for a rough draft. It's using `graphiql`, but it's not optimized for documentation viewing. Looking for ideas or other options for a more optimal schema docs viewing experience. [Graphdoc](https://github.com/2fd/graphdoc) seems like an optimal experience, but is statically generated. Having something that renders the spec on the fly would be ideal (like `graphiql` does). Looks like they are working on a complete rewrite for v2, but I'm not sure on that timeline.

## Context

^^
