### ISSUE TITLE
Unable to add Azure example locations to app-config.yaml

### ISSUE THREAD

**Issue by mfrinnstrom** [spotify/backstage#2306]
It seems adding Azure repos as example locations to the app-config.yaml is not working. It appears to be blocked by the CONFIG_KEY_PART_PATTERN. Since this is because of the slash (/) character I guess BitBucket examples will have the same problem.

## Expected Behavior
Being able to add config like the following:
```
catalog:
  exampleEntityLocations:
    'azure/api':
      - https://dev.azure.com/{organization}/{project}/_git/{repo}?path={path}
```

## Current Behavior

I get the following error:
```
Invalid config key 'azure/api'
```

## Possible Solution

Update the `CONFIG_KEY_PART_PATTERN` I guess. Not sure if this is a good idea though and depending on what the long-term thinking around exampleEntityLocations is it might not be worth the effort.

**Comment by freben** [comment]
Hi!

Hm, that's unfortunate. @Rugvip would it be OK to add slashes to the allowed pattern? We use dots as level separators in compound keys, don't we?

Another solution would be if I changed the format of that section instead, so it's

```yaml
catalog:
  exampleEntityLocations:
    - azure/api:https://dev.azure.com/{organization}/{project}/_git/{repo}?path={path}
```

or

```yaml
catalog:
  exampleEntityLocations:
    - type: azure/api
      target: https://dev.azure.com/{organization}/{project}/_git/{repo}?path={path}
```

the latter would actually be more in line with the similar `catalog.locations` config as well...
