### ISSUE TITLE
[RFC] Extending the scaffolder 

### ISSUE THREAD

**Issue by emmaindal** [spotify/backstage#2447]
## Background

Reading the [software-templates documentation](https://backstage.io/docs/features/software-templates/extending/extending-index), the scaffolder backend is built up by three different stages. `Prepare`, `Templater` and `Publish`. If you want to use your own template you can create a new `Templater`. And if you want to use an already existing one, for example `cookiecutter`, you configure that in the `template.yaml` file.  Something like: 
```
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: react-ssr-template
spec:
  owner: web@example.com
  templater: cookiecutter
  type: website
  path: '.'
  schema:
    required:
      - component_id
    properties:
      component_id:
        title: Name
        type: string
        description: Unique name of the component
```

## Problem

Let's say you want to extend an already existing template (cookiecutter), with the necessary setup to get a techdocs site for your project.

What you can do is:

1.  Use the cookiecutter template and manually add a docs folder with markdown files, a mkdocs.yaml file and techdocs-ref in the component.yaml file together with the rest of the boilerplate content. This has to be added by hand to every template you have (e.g. React SSR template, gRPC template) and also changed by hand in all of the templates if the current docs setup changes. _This is our current process for adding techdocs as default to the different sample templates._ 

To avoid adding the same docs setup to your different templates you could maybe do something like:

2.  Create a duplicated cookiecutter templater class with your additional functionality and use that one (e.g. `cookiecutter-with-docs`) for only the templates that you want documentation to.

3.  Adjust the cookiecutter templater class that already exist (`cookiecutter.ts`) and add your additional functionality (to generate docs setup) and keep use it for all of the templates that are created using the `cookiecutter` templater.

With 2. and 3, you need to modify all of your different Templaters (e.g cookiecutter, cra) to have that additional step.

All of the three options above also give you documentation as default without an option (when creating a new component based on a template). Which could be what we want for the majority of the components we create through our templates, but there could also be exceptions where we want to create a component without documentation.

## Proposal

Here is a proposal to lower the steps you need to take to add documentation to a specific template.

Adjusting the processor to take in another additional stage that are responsible to generate the necessary setup to get a techdocs site into the result directory from the templater step. Something like:

<img width="690" alt="Screen Shot 2020-09-13 at 3 41 01 PM" src="https://user-images.githubusercontent.com/25153114/93019487-941e2a00-f5d7-11ea-9994-dc6fa16dd5d1.png">

This should be an optional step that only gets triggered when documentation is configured in your `template.yaml` file.

That could look something like this:

```
spec:
 owner: web@example.com
 templater: cookiecutter
 type: website
 documentation: default-docs
 path: '.'
 schema:
   required:
     - component_id
   properties:
     component_id:
       title: Name
       type: string
       description: Unique name of the component
```

When this step is configured in the `template.yaml` file, the processor adapt to use the documentation stage with the type `default-docs`. 

## Pros?

As a template creator, you only need to care about the `template.yaml` file and add one line to get the default techdocs setup.

As a template creator, you can decide which type of documentation that should be generated. For example if you would like to have the `default-docs` setup generated or something like `service-docs`, or `golden-path-docs`. Which will most likely have a very different setup of markdown files and structure than the `default-docs` type. But you are still able to use the same `service-docs` type in all of your 5 different types of service templates. (This also gives us the opportunity to open up a new world of different documentation setups that we and the community can contribute to). 

## Cons?

You always need to configure the documentation key in your `template.yaml` file to get documentation generated for your template. 

Would love to start a discussion around this here to collect more ideas on how this problem can be solved. So that we can make the step of adding documentation to specific templates easier and a part of the scaffolder flow.

cc @spotify/techdocs-core for comments 

#### _Additional discussion topic: Improve the template creator experience further_

_What if the backstage CLI provides a similar way to create-plugin but for templates? This means you could run backstage-cli `create-template`, get to specify if you want to create a new template or extend an already existing one as well as get exposed to a set of configurations to choose from (e.g documentation)._
