### ISSUE TITLE
Support for dotenv

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2521]
I was going to ask this in Discord but decided to do it here in case others have the same question.

[dotenv](https://www.npmjs.com/package/dotenv) is a popular mechanism of specifying project-specific environment variables without accidentally adding secrets to git history. It relies on git ignored `.env` file with environment variables. 

Backstage has it's own configuration reading API. In theory, dotenv and Backstage config should not be in conflict as long as dotenv is loaded before Backstage config. At the same time, adding secret environment variables directly to `app-config.development.yaml` and git ignoring `app-config.development.yaml` would serve the same functionality as dotenv.

What are your thoughts on how app-config.development.yaml should be used and the role of .env if any?

**Comment by Rugvip** [comment]
You can use `app-config.local.yaml` and `app-config.development.local.yaml`! They are ignored by default, and you can put secrets straight up as values.

For example, I use the following in `app-config.local.yaml` to have a separate file with some custom entity definitions for development, as well as Google auth setup:

```yaml
catalog:
  locations:
    ... standard stuff

    - type: file
      target: /Users/me/dev/backstage/dev-components.local.yaml
      rules:
        - allow: [User, Group]

auth:
  providers:
    google:
      development:
        clientId: <numbers>.apps.googleusercontent.com
        clientSecret: <secret-key>
```

Perhaps a "local development configuration" section in the docs would help with visibility?

**Comment by taras** [comment]
This is exactly what I was hoping to find out.

> Perhaps a "local development configuration" section in the docs would help with visibility?

I'll add the docs - if you assign the issue to me.

**Comment by Rugvip** [comment]
Sorry forgot to point to the existing point for the feature: https://backstage.io/docs/conf/writing#file-resolution

Thinking the local development setup could be more clearly explained there, but maybe also that we should mention it in the getting started bit

**Comment by andrewthauer** [comment]
I've been using https://direnv.net to handle this use case. I've found this easier then creating a custom `app-config.local.yaml`, which requires duplicating a bunch of sections from the `app-config.yaml`. Having `dotenv` support would essentially be the same result, but something build in. My 2 cents anyways 😄

**Comment by Rugvip** [comment]
@andrewthauer do you have an example of something that requires duplication? From my experience values are either easy to override with a single value, or tricky to configure through environment variables anyway.

Not saying we can't add support for loading in env files, but trying to stay away from too many solutions for the same issue if it doesn't provide additional value.

**Comment by andrewthauer** [comment]
@Rugvip - I'm mostly using environment variables for just supplying a value for an existing `$secret` in the main config file. 

So, instead of having to replicate the full config path like this:

```yaml
# app-config.local.yaml
auth:
  providers:
    google:
      development:
        clientId: 'XXXXXX'
        clientSecret: 'YYYYYY'
```

I can just do:

```sh
# .envrc or .env
export GITHUB_ACCESS_TOKEN="XXXXXX"
export GITLAB_ACCESS_TOKEN="XXXXXX"
```

However, I use `direnv` for all kinds of things so this is natural and works without having to add `dotenv` support :)
