### ISSUE TITLE
Ability to dynamically fetch API spec definition from a URL or a built file

### ISSUE THREAD

**Issue by taras** [spotify/backstage#2572]
Our organization uses GraphQL federation. We have a bunch of services that are federated into a single gateway.
We would like to show schema from these services in the catalog. We use [Nexus](https://nexus.js.org) to express schema as TypeScript and compile the TypeScript to GraphQL SDL.

## Feature Suggestion

We need a way to get the schema from the result of a build. In our case, the schema for each service is available on the service running in QA, inside of the GitHub Action while preparing tests and in Jenkins when building docker images. We need a way to use schema from one of these methods.

## Possible Implementation

1. Allow specifying a URL where the schema can be fetched from

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-federated-service
spec:
  type: graphql-federated-service
  definition:
    url: https://my-federated-service.my-cloud.com/graphql
```

One challenge that I see with this approach is that we're not going to have a clear relationship between schema in QA and Git commit that schema was built from.

2. We could not change anything and update the catalog whenever we build the service in GitHub Actions or Jenkins. This seems less preferable because it'll require configuring each service per repository. This mechanism could become fragile because it might stop updating and no one will know.

3. Have some way to build the code while fetching schema updates. I'm not sure how this would work.

**Comment by Fox32** [comment]
Yeah allowing to load the definition from a url is something we would like to implement too. But I would prefer to reuse the location processors for this: It would be useful to load the definition from locations like GitHub repositories, files, or other locations too.

I hope this is something we can completely implement in the processors, so that we load the definition into the entity.

**Comment by freben** [comment]
Yeah my initial rough idea was that you could define that API as something along the lines of

```yaml
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-federated-service
  annotations:
    backstage.io/graphql-schema-source: https://my-federated-service.my-cloud.com/graphql
spec:
  type: graphql-federated-service
```

Note the annotation. And then a processor would inject the actual definition based on what was introspected from that endpoint.

For schemas that are next to the `catalog-info.yaml` file, one could have an annotation `backstage.io/file-source: ./openapi.json` or something like that. We could make it know how to resolve relative paths to the current location, and then leverage the already existing processors to read the data out of the resulting absolute URL.
