### ISSUE TITLE
TechDocs: Cannot view document from Github private repository

### ISSUE THREAD

**Issue by amarruedo** [spotify/backstage#2964]
## Expected Behavior

I should be able to view the documented-component page.

## Current Behavior

- Received an ERROR 404: Documentation not found.
- Browser console shows a CORS error at the end.

![imagen](https://user-images.githubusercontent.com/58252209/96431656-1f589400-1204-11eb-83d2-a07d7037dd3e.png)

## Steps to Reproduce

Navigate to `my.backstage.com/docs` on browser and click Read Docs under documented-component

## Context

Trying to view Techdocs

## Your Environment

I've deployed Backstage on our internal Kubernetes cluster. 
I've built docker images based on what is on master@ac8d5d5c74bbc073d6d1f372ce15b8b2cffb3e52
I run the following on the building process:
```
yarn install
yarn tsc
# frontend
yarn run docker-build:app
# backend
yarn docker-build -f contrib/docker/kubernetes-example-backend/Dockerfile
```
Resulting in [frontend](https://hub.docker.com/r/saltosystems/backstage) and [backend](https://hub.docker.com/r/saltosystems/backstage-backend) images, being tag `676f49ea6fe0266a170b755397ddb808c5fc6961` the tag currently I'm using. 

Techdocs relevant app-config:
```
techdocs:
  storageUrl: https://my.backstage.com/api/techdocs/static/docs
  requestUrl: https://my.backstage.com/api/techdocs
  generators:
    techdocs: local
```
Kubernetes relevant config:
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backstage-backend
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  tls:
  - hosts:
    - my.backstage.com
    secretName: backstage-production-letsencrypt
  rules:
  - host: my.backstage.com
    http:
      paths:
      - backend:
          serviceName: backstage-backend
          servicePort: backend
        path: /api(/|$)(.*)

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: backstage-frontend
  annotations:
    kubernetes.io/tls-acme: "true"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - my.backstage.com
    secretName: backstage-production-letsencrypt
  rules:
  - host: my.backstage.com
    http:
      paths:
      - backend:
          serviceName: backstage
          servicePort: frontend
        path: /
```
I'm not sure if this is a bug or if this is related to a misconfiguration on my side, since I can see requests to `localhost:3003` inestead to `my.backstage.com`. Any ideas?

Related issue #2736
