### ISSUE TITLE
Question regarding scaffolding and Azure DevOps

### ISSUE THREAD

**Issue by mfrinnstrom** [spotify/backstage#2996]
With the switch to the `integrations` part of the `app-config.yaml` I have a question.

I started to move over my init code from `plugins/scaffolder.ts` to read from the `integrations` part instead of the `scaffolder` part of the config.

I can only set the `host` to `dev.azure.com` right now. That means I can read part of the needed config from here. But I need to read the `baseUrl` from the scaffolder part.

```
integrations:
  azure:
    - host: dev.azure.com # This is the only allowed value for now
      token:
        $env: AZURE_TOKEN

scaffolder:
  azure:
    baseUrl: https://dev.azure.com/{your-organization} # This is needed to create the GitApi client used to create the repos when publishing
    api:
      token:
        $env: AZURE_TOKEN
```

So my question is what the plans are for this going forward? Should the `baseUrl` be kept in the `scaffolder` part of the config and then match that against the `host` in the `integrations` part to get the token? I'm not really sure how the integrations part should be used.
