### ISSUE TITLE
Support configurable working directory for scaffolder

### ISSUE THREAD

**Issue by mfrinnstrom** [spotify/backstage#2998]
## Feature Suggestion

We would like to be able to configure the working directory for the scaffolder. Right now it uses the OS temp-dir. By introducing an optional config for this and fall back to the OS temp-dir if not configured this could be introduced without affecting existing configurations.

```
scaffolder:
  workingDirectory: /some-directory # fall back to OS temp-dir if not configured
  azure:
    baseUrl: https://dev.azure.com/{your-organization}
    api:
      token:
        $env: AZURE_TOKEN
```

## Possible Implementation

I see two options here:

1. Introduce a base class for all preparers that handles this
2. Create a helper and make sure that all preparers use that

I lean more towards a base class since the ownership of the configuration seems a bit more clear than if a "random" helper reads from the scaffolder part of the config (it might also be that I come from a Java background as well). I have however seen more helpers than inheritance in the parts of the code that I have touched.

I can do the implementation if you just tell me which direction you prefer.

## Context

Our Backstage app will be running using ECS Fargate on AWS. I'm now looking into running the `templater` step of the scaffolder using ECS Fargate as well instead of a local Docker instance. To make it easy to share the prepared files (that are downloaded in the Backstage container) with the `templater` step that will run in a separate container we intend to use EFS and mount a shared filesystem between the containers.
