### ISSUE TITLE
Importing error does not match validation rules

### ISSUE THREAD

**Issue by dtuite** [spotify/backstage#3092]
When you try to import a `catalog-info.yaml` will an uppercase tag into Backstage you get the following error:

```
InputError: "tags.1" is not valid; expected a string that is sequences of [a-zA-Z0-9] separated by [-], at most 63 characters in total but found "OSS". To learn more about catalog file format, visit: https://github.com/spotify/backstage/blob/master/docs/architecture-decisions/adr002-default-catalog-file-format.md at inputError (/usr/src/app/plugins/catalog-backend/dist/index.cjs.js:728:12) at LocationReaders.handleEntity (/usr/src/app/plugins/catalog-backend/dist/index.cjs.js:898:12) at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

The error says that uppercase chars are valid, even though it is rejecting them. This is what I'm trying to import:

```yaml
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-plugin-aws-auth
  description: |
    Backstage plugin to authenticate other plugins with AWS IAM.
  annotations:
    github.com/project-slug: roadiehq/backstage-plugin-aws-auth
  tags:
    - plugin
    - OSS
spec:
  type: library
  owner: group:roadie
  lifecycle: experimental
```

Changing to this allows the import to succeed:

```yaml
# ...
  tags:
    - plugin
    - oss
spec:
# ...
```

Screenshot of the error:

![Screenshot 2020-10-26 at 09 00 36](https://user-images.githubusercontent.com/562403/97153446-64cc1280-176a-11eb-83ab-e778b13eea61.png)

**Comment by dtuite** [comment]
Probably a good candidate for "Good First Issue". I can't add labels.

**Comment by vividh** [comment]
Hi, may I claim this issue? Also, could you help with the steps to replicate this, since I'm completely new to this project?

**Comment by freben** [comment]
Assigned!

simplest is probably to make an `app-config.local.yaml` file, and add

```yaml
catalog:
  locations:
    - type: file
      target: /some-path-to/faulty-component.yaml
```

When you start the backend, it should ingest that file and you should be able to see the error
