### ISSUE TITLE
catalog backend: decide on descriptor file format

### ISSUE THREAD

**Issue by freben** [spotify/backstage#767]
The catalog service will index files stored in a version control system. Decide on the format for these files, and therefore, also on the information model of what constitutes a component.

Initial Minimum Lovable Product requirements:

- Text based, easily writable and readable by humans
- Easily machine readable and verifiable
- Versioned, such that the format can change while newer inventory services still can ingest older format files
- Contains at least the following metadata:
  - A name or ID, identifying the component
  - A description
- Contains at least the following non-normative data:
  - TBD
- Contains at least the following normative actual specification data:
  - A type (possible suggestions: "service", "website", etc)
  - An owner (possible suggestions: email, LDAP group name, etc)

The metadata may be extended to include:

- The name or ID of the system that it belongs to

The specification data may be extended to include:

- A scope (possible suggestions: "external", "internal", etc)
- A lifecycle (possible suggestions: "experimental", "production", etc)

The specification data shall strictly describe the nature of the component itself. It shall not include e.g. references to external resources. It is desirable that there is a clear separation (either through documentation, or in the format itself) between metadata, non-normative and normative information.

**Comment by freben** [comment]
Possible YAML for discussion:

```yaml
apiVersion: inventory.backstage.io/v1
kind: Component
metadata:
  name: edge-auth-proxy
  description: >
    This is the service that ...
spec:
  type: service
```

**Comment by freben** [comment]
More food for thought: https://www.kislayverma.com/post/platform-nuts-bolts-extendable-data-models

**Comment by dtuite** [comment]
[Helm charts](https://helm.sh/docs/topics/charts/) may be somewhat instructive as a case study.

Some thoughts regarding them:

1. `keywords` could provide searchability for humans (see this GitHub repo for example!)
2. `maintainers` - is there value in supporting multiple owners? Providing an LDAP or Active Directory group obviously supports this because you can add and remove people from the LDAP group. Will all companies who want to use Backstage have this though? I'm not too familiar with what smaller companies do.
3. `icon` because humans like logos and they are easy to recognize when you're looking at a list of 40 services.

**Comment by dtuite** [comment]
I like the idea of sticking close to what k8s does for robustness and familiarity.

**Comment by freben** [comment]
Had a look at helm - definitely close to what I had in mind, and interesting possible additions.

## keywords

Can be interesting for mainly human consumption, in general search for example. We've been considering something like [k8s labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) as well, but those would be a bit more formal and could power filters in the frontend. Maybe enable the use of both?

## maintainers

Internally at Spotify, the core of the ownership concept has been very strict: there is only ever one actual responsible owner who is the main point of contact for a component, and it has to be a proper team - not some random group, not an individual, not an entire division etc. This has served us extremely well, but we are looking at whether this translates to everybody out there or if it should be a list, or if it is actually more than one field (e.g. is the tech owner different from the financial sponsor or the point of contact etc). Your input is welcome here!

SIDETRACK ALERT:

You mention the word maintainers. Apart from wording, I think it can be of interest to mention not just the contents of these fields, but their semantics as well.

In our internal implementation, it has been tempting for different people to ascribe their own meanings to existing component fields, or to add their own random fields to these files that even control aspects of the runtime world. This is something that should be done with great care if at all. For example, hypothetically, one part of an organisation could have interpreted the owner field as enabling ssh access for the owner group members to machines where this component is running. Another part of the organisation may have interpreted it as giving edit rights to monitoring dashboards related to the component. And so it goes on and on and grows over time, becoming hard to get an overview of.

I think that as we settle this format, we should also ascribe crystal clear guidelines on the purposes and limitations of these fields. It may be best to steer clear of this type of side effects entirely, and make sure that if you want to bind ACLs to a component, then that should happen elsewhere, not directly derived from this file.

And for the above reasons, wording can be important - if it's named `pointOfContact` instead of `maintainer`, it can change how people consume the field.

But this is an entire discussion topic of its own :)

## icon

Interesting. Maybe? If we had both description, icon and keywords, then this sounds like it would lend itself extremely well to a nice overview page or even for listings.

@stefanalund ^ fyi

**Comment by dtuite** [comment]
@freben 

> SIDETRACK ALERT:

I will keep this brief in the interests of not derailing the issue!

We built a Backstage-like thing in Workday and we did the same as you did at Spotify. Used LDAP group as the concept of ownership. It solves a lot of the headaches in a simple way.

That said, as humans, we do have concepts of roles within a team. PMs, engineers, tech leads etc. If Backstage is attempting to map the infra in a way that humans can grok, it should possibly try to bend to the mental model of the humans rather than making the humans bend to it.

> not living in these files or being part of the core spec

I agree with this. I can visualize a future where the concept of ownership is pulled from a HCM tool (like Workday) rather than flat files in the repo.

> nice overview page or even for listings.

Exactly. 

Where is the best place for these meta-discussions/design-discussions? I appreciate that GitHub issues may not be it.

**Comment by freben** [comment]
You're always welcome in [our discord](https://discord.gg/MUpMjP2) if you're into that! The core team (and many others) hang out there.

**Comment by nikek** [comment]
I find `name` to be having the same issue as the one you describe for `owner`. In this case where there is no `id` field, I assume that `name` is both supposed to solve the identifier string problem like what you find in urls, but also the human readable title of a component presented in UIs. I'd like to separate those two by having clear fields like
- `displayName`, a title that can be used in UIs, like in h1 or lists.
- `id`, a unique and url friendly key used to identify a component programatically.

**Comment by Rugvip** [comment]
@nikek tbh the id is what we use as the human-readable version internally :grin:

**Comment by freben** [comment]
Yeah, there's no human readable name considered so far - do you think there should be one?

The choice of `name` is because it aligns with the very well known kubernetes formats.

**Comment by freben** [comment]
And I think the kubernetes designers chose it for fairly good reason - IDs are expected to be truly machine-only opaque identifiers, like the uuids generated for added locations. And name is the "human readable id"

**Comment by nikek** [comment]
I'd love for the separation of responsibilities between two fields. I'm also taking inspiration from  how the blog world handles urls with "slugs" generated from the title of the blog post. In that case the title comes first and the url friendly identifier comes second with added dashes and lowercased and stripped characters.

I envision `displayName` to become a bit more human friendly and creative like `Magic Pub/Sub Service 🧙‍♂️"
and the `id`: `magic-pubsub-service`

If you think this is weird and adds complexity to the schema I'm fine with postponing it to a future addition to the schema, where there potentially is a more detailed doc describing how it would be implemented and what the benefits are in various use-cases.

**Comment by nikek** [comment]
Also, I must say that I find the kubernetes format to be a bit odd. I'm reading the file as `apiVersion` and `kind` is the main data and additionally, there is metadata, which from my perspective is the data I'm most often really after. How come `name` is not in the top level of the file, isn't that what this file is really about?

**Comment by mbruggmann** [comment]
Playing a bit more on the example yamls.

Code component:
```yaml
apiVersion: backstage.io/v1
kind: Component
metadata:
  name: edge-auth-proxy
  labels:
    system: auth
    owner: infra-ops@example.com
  annotations:
    github.repo-url: github.com/org/repo
    github.descriptor-path: kubernetes/backstage-component.yaml
    k8s.namesapce: namespace
    k8s.service-name: edge-auth-proxy
spec:
  type: service
  url: github.com/org/repo/component-xy/
  description: >
    This is the service that ...
```

API:
```yaml
apiVersion: backstage.io/v1
kind: API
metadata:
  name: edge-api
  labels:
    system: auth
    owner: infra-ops@example.com
  annotations:
    github.repo-url: github.com/org/repo/
    github.descriptor-path: kubernetes/backstage-api.yaml
spec:
  type: grpc
  url: github.com/org/repo/component-xy/proto/api.proto
```

Resource:
```yaml
apiVersion: backstage.io/v1
kind: Resource
metadata:
  name: edge-db
  labels:
    system: auth
    owner: infra-ops@example.com
  annotations:
    github.repo-url: github.com/org/repo/
    github.descriptor-path: kubernetes/backstage-resource.yaml
spec:
  type: postgres
  url: cloud.google.com/sql/<my-instance>:port
```

Basing this on the Kubernetes resource format: https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/. Primarily to put things that we select by into `metadata.labels`, plugin-specific identifiers into annotations, and kind-specific data into `spec`.

**Comment by Rugvip** [comment]
Just had a discussion around k8s-style multi-document approach vs docker-compose-style top-levels keys with multiple entries. For example

```yaml
---
kind: system
name: <system-name>
data: <system-data>
---
kind: component
name: <component-name>
data: <component-data>
```

vs

```yaml
systems:
  <system-name>: <system-data>

components:
  <component-name>: <component-data>
```

And somewhat concluded that the k8s-style approach fits us better, as almost all files will just contain a single component anyway. k8s-style also gives much nicer separation of api versioning and isn't as messy to extend.

**Comment by mbruggmann** [comment]
+1 for multi-document or multi-file approach (vs top-level keys).

**Comment by freben** [comment]
@nikek This is intentional, and matches the sentiment at the bottom of the initial text: "It is desirable that there is a clear separation (either through documentation, or in the format itself) between metadata, non-normative and normative information."

If you look at the modelling of things like this, it can be argued that primary keys and relations are NOT part of the model itself. You can change the contents of the spec all you like, that "is the thing". Is "freben" part of what constitutes "me", or is it just a pointer in the metadata? Is it just another label to order and filter things by?

**Comment by freben** [comment]
@mbruggmann There have been discussions about what to put in `metadata.labels` and what to put in `spec`. In your example you put `system: auth` among the labels, and I instinctively did the same first, but there were some sentiments fed back to us that the system ref is part of the actual component model and therefore should live in `spec` -- and that labels are nothing but loosely coupled filter variables that can't be "relied on", so to speak. I now put the same field directly in `metadata`, not under labels, as a middle ground. How do you feel about this aspect of the model?

You also put github metadata under `metadata.annotations`. While I understand the sentiment, I wonder: is this something you see as part of the actual files on e.g. github, typed by humans? Or are they inserted at ingestion time automatically by the code that fetched the yaml file, effectively into the yaml itself before it hits the catalog API? Or is it actually a piece of auxiliary data, not part of the yaml model at all, that can be pushed separately (as a free floating "fact"), and then only merged in when querying for components (and therefore only are part of the "response model")?

**Comment by Rugvip** [comment]
Building on @mbruggmann example, applying the mult-document approach to facts/annotations, and bringing in ideas from the linked article:

```yaml
kind: component
metadata:
  name: edge-auth-proxy
  labels:
    system: auth
    owner: infra-ops@example.com
facts:
  - type: presentation.v1
    title: Edge Auth Proxy
    description: >
      This is the service that ...
    icon: ./path/to/icon.svg

  - type: git.v1
    url: github.com/org/repo/component-xy/

  - type: github.v1
    repo-url: github.com/org/repo
    descriptor-path: kubernetes/backstage-component.yaml

  - type: k8s.v1
    namespace: namespace
    service-name: edge-auth-proxy
```

The metadata object being the core platform model, and the facts the data for different domains. Using an array of fact bundles instead of encoding that into object keys.

You could go more verbose and wrap facts in the spec object, and put the fact data inside a data field alongside the type, but I don't think that's needed.
